// widget_test.dart
//
// A basic smoke test confirming the app boots and lands on the Dashboard
// placeholder. Replaces the default counter-app test generated by
// `flutter create`, which tested code that no longer exists. This should be
// expanded as real screens replace the placeholders.

import 'package:flutter_riverpod/flutter_riverpod.dart';
import 'package:flutter_test/flutter_test.dart';

import 'package:shift_companion/app.dart';

void main() {
  testWidgets('App launches to the Dashboard placeholder', (
    WidgetTester tester,
  ) async {
    // ProviderScope is required here for the same reason it's required in
    // main.dart: ShiftCompanionApp reads Riverpod providers (e.g. the
    // router) that only exist within a scope.
    await tester.pumpWidget(
      const ProviderScope(child: ShiftCompanionApp()),
    );
    await tester.pumpAndSettle();

    // The Dashboard's AppBar title confirms the router launched to the
    // correct initial route.
    expect(find.text('Dashboard'), findsOneWidget);
  });
}
