// widget_test.dart
//
// A basic smoke test confirming the app boots, lands on the Dashboard, and
// that the bottom-navigation shell (added in Phase 2.1, see
// routing/app_shell.dart) renders both tabs. Replaces the default
// counter-app test generated by `flutter create`, which tested code that no
// longer exists. This should be expanded as more screens replace
// placeholders.

import 'package:flutter_riverpod/flutter_riverpod.dart';
import 'package:flutter_test/flutter_test.dart';

import 'package:shift_companion/app.dart';

void main() {
  testWidgets('App launches to the Dashboard with both nav tabs visible', (
    WidgetTester tester,
  ) async {
    // ProviderScope is required here for the same reason it's required in
    // main.dart: ShiftCompanionApp reads Riverpod providers (e.g. the
    // router) that only exist within a scope.
    await tester.pumpWidget(const ProviderScope(child: ShiftCompanionApp()));
    await tester.pumpAndSettle();

    // The Dashboard has no AppBar by design (see GreetingHeader's doc
    // comment), so these two checks — rather than a screen title — are
    // what confirm the router launched to the correct initial route: the
    // bottom NavigationBar's "Dashboard" label, and the Calendar tab
    // sitting alongside it, both present from first launch.
    expect(find.text('Dashboard'), findsOneWidget);
    expect(find.text('Calendar'), findsOneWidget);
  });
}
